### ISSUE TITLE
Remove the focus

### ISSUE THREAD

**Issue by chprome** [bosonic-labs/b-toggle-button#2]
When clicking on the toggle, it gets the focus.
It doesn't give a nice user XP

Actual
![focus](https://cloud.githubusercontent.com/assets/1465463/3185673/6b5b588c-ec96-11e3-970a-1e4bd8ca006e.png)

Expected
![nofocus](https://cloud.githubusercontent.com/assets/1465463/3185672/698c23ba-ec96-11e3-94ad-4b5464125c8a.png)

**Comment by goldoraf** [comment]
Getting the focus is part of accessibility rules on this kind of component, therefore we can't remove it. You can "hide" the dotted border in your app's CSS though, even if it's considered a bad a11y pratice:

``` css
b-toggle-button:focus {
  outline: 0;
}
```
